name: Check birthdays everyday and submit notifications
on:
  schedule:
    - cron: '30 4 * * *'  # every day early in the morning
  workflow_dispatch:
jobs:
  run:
    name: Deploy updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run
        run: node dist/bin.js --dbpath ./db.csv --slack-token ${{ secrets.SLACK_TOKEN }} --slack-conversation-id ${{ secrets.SLACK_CONVERSATION_ID }}

